"       _
"__   _(_)_ __ ___  _ __ ___
"\ \ / / | '_ ` _ \| '__/ __|
" \ V /| | | | | | | | | (__
"  \_/ |_|_| |_| |_|_|  \___|
"

let mapleader = ","

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'wincent/command-t'
Plug 'sjbach/lusty'
Plug 'vim-scripts/cscope.vim'
Plug 'Valloric/YouCompleteMe'
Plug 'tpope/vim-fugitive'
Plug 'vim-syntastic/syntastic'
Plug 'mileszs/ack.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'craigemery/vim-autotag'
Plug 'vim-scripts/taglist.vim'
call plug#end()

" basic stuff
set hidden
syntax on
set number
:set expandtab
set tabstop=4
set shiftwidth=4
set hlsearch
set incsearch
set noeb vb t_vb=
" autocmd VimEnter * NERDTree

" mappings
map <silent> <C-n> :NERDTreeToggle<CR>

let g:ackprg = 'ag --vimgrep --smart-case'
cnoreabbrev ag Ack
cnoreabbrev aG Ack
cnoreabbrev Ag Ack
cnoreabbrev AG Ack

let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'

let Tlist_Use_Right_Window   = 1
autocmd FileType c,cpp,h TlistOpen
