"       _
"__   _(_)_ __ ___  _ __ ___
"\ \ / / | '_ ` _ \| '__/ __|
" \ V /| | | | | | | | | (__
"  \_/ |_|_| |_| |_|_|  \___|
"

let mapleader = ","

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'wincent/command-t'
Plug 'sjbach/lusty'
call plug#end()

" basic stuff
set hidden
syntax on
set number
:set expandtab
set tabstop=4
set hlsearch
set incsearch

" mappings
map <silent> <C-n> :NERDTreeToggle<CR>
